name: Build and Push x64 Docker Image

on:
  push:
    branches:
      - main # Triggers the build every time you push to the main branch

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }} # This will be 'your-github-username/trackio'

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Native x64 runner
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: actions/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: actions/docker-login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Automatically generated by GitHub

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=latest
            type=sha,format=short

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64 # Forces the x64 architecture build
          tags: ${{ ids.meta.outputs.tags }}
          labels: ${{ ids.meta.outputs.labels }}
          cache-from: type=gha # Speeds up subsequent builds using GitHub cache
          cache-to: type=gha,mode=max
